name: jantung_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.7
  http: ^1.1.0
  jwt_decoder: ^2.0.1
  shared_preferences: ^2.2.1
  flutter_spinkit: ^5.2.0
  get_storage: ^2.1.1
  animated_bottom_navigation_bar: ^1.3.0
  image_picker: ^1.0.4
  file_picker: ^8.0.0+1
  intl: ^0.17.0
  video_player: ^2.8.5
  path_provider: ^2.1.3
  video_trimmer: ^2.0.1
  url_launcher: ^6.2.4
  device_apps: ^2.2.0
  android_intent_plus: ^5.0.2
  chewie: ^1.7.5
  ffmpeg_kit_flutter: ^5.1.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/font/poppins/Poppins-Regular.ttf
        - asset: assets/font/poppins/Poppins-Bold.ttf
        - asset: assets/font/poppins/Poppins-Italic.ttf

    #  -assets/font/poppins/
  #- images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
